In [1]:
import numpy as np

### Write a function so that the columns of the output matrix are powers of the input
### vector.
### The order of the powers is determined by the increasing boolean argument. Specifically, when
### increasing is False, the i-th output column is the input vector raised element-wise to the power
### of N - i - 1.

### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
### Theophile Vandermonde.

In [48]:
def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx



In [49]:
inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

inputvector = np.array([1,2,4,6,8,10])
no_col_opmat = 5
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)



The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



### Question: Write a function to find moving average in an array over a window:
### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [36]:
#function 

def moving_average(k,lst):
    n=len(lst)
    x=0
    foo=[]
    for i in range(n-k+1):
        g=lst[x:x+k].sum()
        x=x+1
        foo.append(g)

    return foo
    
    

In [34]:
lst= np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3

In [35]:
moving_average(k,lst)

[15, 14, 17, 20, 29, 86, 148, 218, 252, 280, 349]

In [46]:
ipvector = np.array([1,2,3,4,5])
n = 3

In [47]:
[x**i for x in ipvector for i in range(n)]

[1, 1, 1, 1, 2, 4, 1, 3, 9, 1, 4, 16, 1, 5, 25]